routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->middleware(['CheckStatus','auth','CheckEntry'])->name('home');
Route::post('/users/store','UserController@store')->name('users.store');

Route::middleware(['auth','role:super-admin|administrador','CheckStatus','CheckEntry'])->prefix('users')->name('users.')->group(function(){
    Route::get('/', 'UserController@index')->name('index');
    Route::get('/user/{id}','UserController@show')->name('show')->where('id','[0-9]+');
    Route::get('/user/{id}/edit','UserController@edit')->name('edit')->where('id','[0-9]+');
    Route::get('/user/{id}/roles','UserController@roles')->name('roles');

    Route::post('/disable','UserController@disable')->name('disable');
    Route::post('/enable','UserController@enable')->name('enable');
    Route::post('/destroy','UserController@destroy')->name('destroy');
    Route::post('/authorize','UserController@authorizeAccount')->name('authorize');
    Route::post('/update/{id}','UserController@update')->where('id','[0-9]+')->name('update');
    Route::post('/roles/{id}/update','UserController@update_roles')->where('id','[0-9]+')->name('roles.update');
});

Route::middleware(['auth','role:super-admin|administrador','CheckStatus','CheckEntry'])->prefix('attendances')->name('attendances.')->group(function(){
    Route::get('/','AttendanceController@index')->name('index');
    Route::any('/registers','AttendanceController@registers')->name('registers');

    Route::post('/store','AttendanceController@store')->name('store');
    Route::post('departiture','AttendanceController@departiture')->name('departiture');
});

Route::middleware(['auth','role:super-admin|administrador|cocina','CheckStatus','CheckEntry'])->prefix('stews')->name('stews.')->group(function(){
    Route::get('/','StewController@index')->name('index');

    Route::post('/store','StewController@store')->name('store');
    Route::post('/disable/{id}','StewController@disable')->name('disable')->where('id','[0-9]+');
    Route::post('/enable/{id}','StewController@enable')->name('enable')->where('id','[0-9]+');
});

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use Notifiable;
    use HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Mail;
use Illuminate\Validation\Rule;
use App\Mail\AuthorizedAccount;
use App\User;

class UserController extends Controller
{
    public function index(Request $request)
    {
        $search = $request->input('search');
        $users = User::where(DB::raw("CONCAT(name,'',names,'',paternal_surname,'',maternal_surname,'',email,'',phone)"),'like',"%$search%")->paginate(15);

        return view('Users.index', compact('users','search'));
    }

    public function create()
    {
        //
    }

    public function roles($id)
    {
        $user = User::findOrfail($id);
        $roles = array();
        foreach ($user->getRoleNames() as $role) {
            array_push($roles, $role);
        }
        return view('Users.roles', compact('user','roles'));
    }

    public function update_roles(Request $request, $id)
    {
        $user = User::whereId($id)->first();

        $roles = json_decode($request->roles);

        foreach($roles as $role){
            if($role->current_role){
               $user->assignRole($role->name);
            }else{
                $user->removeRole($role->name);
            }
        }

        return response()->json(['response' => true], 200);
    }

    public function store(Request $request)
    {
        $request->validate([
            'names'                 => 'required',
            'paternal_surname'      => 'required|alpha',
            'maternal_surname'      => 'required|alpha',
            'birthdate'             => 'required|date|date_format:"Y-m-d"',
            'nationality'           => 'required|alpha',
            'marital_status'        => 'required',
            'rfc'                   => 'required|alpha_num|min:12|max:13',
            'phone'                 => 'required|numeric|digits:10',
            'medical_insurance'     => 'required|numeric|digits:11',
            'emergency_contact'     => 'required',
            'contact_number'        => 'required|numeric|digits:10',
            'medication'            => 'nullable|alpha_num',
            'street'                => 'required',
            'gender'                => 'required',
            'neighborhood'          => 'required',
            'external_number'       => 'required|numeric',
            'internal_number'       => 'nullable|alpha_num',
            'zipcode'               => 'required|numeric|digits:5',
            'name'                  => 'required|alpha_num|unique:users,name',
            'email'                 => 'required|email|unique:users,email',
            'password'              => 'required|min:8',
            'password-confirmation' => 'required|same:password',
            'policy-privacy'        => 'accepted',
        ],[
            'names.required'                 => 'El nombre es requerido',
            'paternal_surname.required'      => 'El apellido paterno es requerido',
            'paternal_surname.alpha'         => 'El apellido paterno no puede contener caracteres especiales',
            'maternal_surname.required'      => 'El apellido materno es requerido',
            'maternal_surname.alpha'         => 'El apellido materno no puede contener caracteres especiales',
            'birthdate.required'             => 'La fecha de nacimiento es requerida',
            'birthdate.date'                 => 'La fecha de nacimiento no es válida',
            'birthdate.date_format'          => 'El formato de la fecha de nacimiento no es válido',
            'nationality.required'           => 'La nacionalidad es requerida',
            'nationality.alpha'              => 'La nacionalidad no puede contener caracteres especiales',
            'marital_status.required'        => 'El estado civil es requerido',
            'rfc.required'                   => 'El RFC es requerido',
            'rfc.alpha_num'                  => 'El RFC no puede contener caracteres especiales',
            'rfc.min'                        => 'El RFC debe tener mínimo 12 caracteres',
            'rfc.max'                        => 'El RFC debe contener máximo 13 caracteres',
            'gender.required'                => 'El campo sexo es requerido',
            'phone.required'                 => 'El teléfono es requerido',
            'phone.numeric'                  => 'El teléfono no es válido',
            'phone.digits'                   => 'El teléfono debe contener 10 números',
            'medical_insurance.required'     => 'El N° de seguro social es requerido',
            'medical_insurance.numeric'      => 'El N° de seguro social no es válido',
            'medical_insurance.digits'       => 'El N° de seguro social debe contener 11 caracteres',
            'emergency_contact.required'     => 'El contacto de emergencía es requerido',
            'contact_number.required'        => 'El teléfono de emergencía es requerido',
            'contact_number.numeric'         => 'El teléfono de emergencía no es válido',
            'contact_number.digits'          => 'El teléfono de emergencía debe ser númerico',
            'medication.alpha_num'           => 'La medicación no debe contener caracteres especiales',
            'street.required'                => 'El nombre de la calle es requerido',
            'external_number.required'       => 'El número exterior es requerido',
            'external_number.numeric'        => 'El número exterior no es válido',
            'internal_number.alpha_num'      => 'El número exterior no puede contener caracteres especiales',
            'zipcode.required'               => 'El código postal es requerido',
            'zipcode.numeric'                => 'El código postal no es válido',
            'zipcode.digits'                 => 'El código postal debe contener 5 caracteres',
            'name.required'                  => 'El nombre de usuario es requerido',
            'name.alpha_num'                 => 'El nombre de usuario no debe contener caracteres especiales',
            'name.unique'                    => 'El nombre de usuario ingresado ya está en uso',
            'email.required'                 => 'El correo electónico es requerido',
            'email.email'                    => 'El correo electónico ingresado no es válido',
            'email.unique'                   => 'El correo electónico ingresado ya está en uso',
            'password.required'              => 'La contraseña es requerida',
            'password.min'                   => 'La contraseña debe contener almenos 8 caracteres',
            'password-confirmation.required' => 'La confirmación de contraseña es requerida',
            'password-confirmation.same'     => 'La confirmación de la contraseña no coincide',
            'privacy-policy.accepted'        => 'Debe aceptar las políticas de privacidad para continuar'
        ]);

        $user = new User();
        $user->names             = $request->names;
        $user->name              = $request->name;
        $user->paternal_surname  = $request->paternal_surname;
        $user->maternal_surname  = $request->maternal_surname;
        $user->birthdate         = $request->birthdate;
        $user->nationality       = $request->nationality;
        $user->marital_status    = $request->marital_status;
        $user->street            = $request->street;
        $user->neighborhood      = $request->neighborhood;
        $user->external_number   = $request->external_number;
        $user->internal_number   = $request->internal_number;
        $user->zipcode           = $request->zipcode;
        $user->gender            = $request->gender;
        $user->rfc               = $request->rfc;
        $user->phone             = $request->phone;
        $user->email             = $request->email;
        $user->medical_insurance = $request->medical_insurance;
        $user->emergency_contact = $request->emergency_contact;
        $user->contact_number    = $request->contact_number;
        $user->medication        = $request->medication;
        $user->admission_date    = date('Y-m-d');
        $user->password          = bcrypt($request->password);

        $user->save();

        $user->assignRole('mesero');

        return redirect()->route('login')->withStatus('Datos registrados correctamente, se requiere aprovación del administrador para continuar.');
    }

    public function show($id)
    {
        $user = User::findOrfail($id);
        return view('Users.show', compact('user'));
    }

    public function edit($id)
    {
        $user = User::findOrfail($id);
        return view('Users.edit', compact('user'));
    }

    public function update(Request $request, $id)
    {
        $request->validate([
            'names'                 => 'required',
            'paternal_surname'      => 'required|alpha',
            'maternal_surname'      => 'required|alpha',
            'birthdate'             => 'required|date|date_format:"Y-m-d"',
            'nationality'           => 'required|alpha',
            'marital_status'        => 'required',
            'rfc'                   => ['required','alpha_num','min:12','max:13', Rule::unique('users')->ignore($id)],
            'phone'                 => 'required|numeric|digits:10',
            'medical_insurance'     => 'required|numeric|digits:11',
            'emergency_contact'     => 'required',
            'contact_number'        => 'required|numeric|digits:10',
            'medication'            => 'nullable|alpha_num',
            'street'                => 'required',
            'gender'                => 'required',
            'neighborhood'          => 'required',
            'external_number'       => 'required|numeric',
            'internal_number'       => 'nullable|alpha_num',
            'zipcode'               => 'required|numeric|digits:5',

resources/views/Users/authorize.blade.php
<div class="modal fade" tabindex="-1" id="authorize" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content modals">
            <div class="modal-header">
                <h5 class="modal-title">{{__('ATENCIÓN')}}</h5>
                <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="{{route('users.authorize')}}" method="post">
                @csrf
                <div class="modal-body text-center">
                    <p>{{__('¿Realmente desea autorizar la cuenta?')}}</p>
                    <input type="hidden" name="id" id="authorize-id">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-link btn-cancelar text-decoration-none" data-dismiss="modal">
                        {{__('CANCELAR')}}
                    </button>
                    <button type="submit" class="btn btn-aceptar" id="btn-authorize">
                        {{__('ACEPTAR')}}
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

resources/views/Users/delete.blade.php
<div class="modal fade" id="delete" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content modals">
            <div class="modal-header">
                <h5 class="modal-title">{{__('ATENCIÓN')}}</h5>
                <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="{{route('users.destroy')}}" method="post">
                @csrf
                <div class="modal-body text-center">
                    <p>{{__('¿Realmente desea eliminar este elemento?')}}</p>
                    <p class="text-danger">{{__('Esta acción no puede revertirse')}}</p>
                    <input type="hidden" name="id" id="delete-id">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-link btn-cancelar text-decoration-none" data-dismiss="modal">
                        {{__('CANCELAR')}}
                    </button>
                    <button type="submit" class="btn btn-aceptar">
                        {{__('ACEPTAR')}}
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

resources/views/Users/disable.blade.php
<div class="modal fade" tabindex="-1" id="disable" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content modals">
            <div class="modal-header">
                <h5 class="modal-title">{{__('ATENCIÓN')}}</h5>
                <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="{{route('users.disable')}}" method="post">
            @csrf
                <div class="modal-body text-center">
                    <p>{{__('¿Realmente desea deshabilitar este elemento?')}}</p>
                    <input type="hidden" name="id" id="disable-id">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-link btn-cancelar text-decoration-none" data-dismiss="modal">
                        {{__('CANCELAR')}}
                    </button>
                    <button type="submit" class="btn btn-aceptar">
                        {{__('ACEPTAR')}}
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

resources/views/Users/enable.blade.php
<div class="modal fade" id="enable" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content modals">
            <div class="modal-header">
                <h5 class="modal-title">{{__('ATENCIÓN')}}</h5>
                <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="{{route('users.enable')}}" method="post">
                @csrf
                <div class="modal-body text-center">
                    <p>{{__('¿Realmente desea activar este elemento?')}}</p>
                    <input type="hidden" name="id" id="enable-id">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-link btn-cancelar text-decoration-none" data-dismiss="modal">
                        {{__('CANCELAR')}}
                    </button>
                    <button type="submit" class="btn btn-aceptar" id="btn-authorize">
                        {{__('ACEPTAR')}}
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

resources/views/Users/index.blade.php
@extends('layouts.app')
@section('lista-personal', 'side-active')
@section('top-title','LISTA DE PERSONAL')
@section('styles')
    <link rel="stylesheet" href="{{asset('css/layouts/index.css')}}">
@endsection
@section('content')

    <div class="container-fluid">
        <div class="row">
            <div class="col-12 px-4 form-row mt-4">
                <div class="col-lg-6 mb-3">
                    <form class="form-row" action="" method="get">
                        <div class="form-group col-11 col-md-8 mb-0 pr-0">
                            <input type="text" class="form-control search-input" name="search" value="{{$search}}" placeholder="Buscar...">
                        </div>
                        <button type="submit" class="btn btn-search col-1">
                            <i class="fas fa-search"></i>
                        </button>
                    </form>
                </div>

                <div class="col-lg-6 text-right px-0">
                    <a href="#" class="btn btn-new-entry rounded-0" data-toggle="tooltip" data-placement="left" data-title="Imprimir PDF">
                        <i class="fas fa-file-pdf"></i>
                    </a>
                    <a href="#" class="btn btn-new-entry px-4 rounded-0">{{__('NUEVO REGISTRO')}}</a>
                </div>
            </div>
            @if($users->count())
                <div class="col-12 table-responsive mt-4">
                    <table class="table">
                        <thead>
                            <tr class="text-center">
                                <th scope="col">#</th>
                                <th>{{__('NOMBRE')}}</th>
                                <th>{{__('ESTATUS')}}</th>
                                <th>{{__('ACCIONES')}}</th>
                            </tr>
                        </thead>
                        @foreach ($users as $user)
                            <tr class="text-center">
                                <td scope="row" class="align-middle text-truncate">
                                    @if(is_null($user->image))
                                        <img src="{{('https://api.adorable.io/avatars/40/').$user->email}}" alt="" class="img-fluid" style="border-radius: 50%">
                                    @else
                                        <img src="{{asset('images/users_images/'.$user->image)}}" alt="" class="img-fluid" style="border-radius: 50%; width: 40px; height:40px" >
                                    @endif
                                </td>
                                <td class="align-middle text-truncate">
                                    {{$user->names." ".$user->paternal_surname." ".$user->maternal_surname}}
                                </td>
                                @if ($user->authorized)
                                    <td class="align-middle text-truncate {{$user->status ? 'table-success' : 'table-danger'}} text-dark">
                                        {{$user->status ? 'ACTIVO' : 'DESACTIVADO'}}
                                    </td>
                                @else
                                    <td class="align-middle text-truncate {{$user->authorized ? 'table-success' : 'table-warning'}} text-dark">
                                        {{$user->authorized ? 'ACTIVO' : 'PENDIENTE'}}
                                    </td>
                                @endif
                                <td class="align-middle text-truncate">
                                    <a href="{{route('users.roles',['id' => $user->id])}}" class="btn btn-link btn-actions" data-toggle="tooltip" data-placement="left" data-title="Roles">
                                        <i class="fad fa-user-shield fa-lg"></i>
                                    </a>
                                    <a href="{{route('users.show', ['id' => $user->id])}}" class="btn btn-link btn-actions" data-toggle="tooltip" data-placement="top" data-title="Información">
                                        <i class="fad fa-user-tag fa-lg"></i>
                                    </a>
                                    @if($user->authorized)
                                        @if ($user->status)
                                            <span class="open-modal" data-toggle="modal" data-target="#disable" data-action="disable" data-id="{{$user->id}}">
                                                <button type="button" class="btn btn-link btn-actions" data-toggle="tooltip" data-placement="top" data-title="Desactivar">
                                                    <i class="fad fa-user-slash fa-lg"></i>
                                                </button>
                                            </span>
                                        @else
                                            <span class="open-modal" data-toggle="modal" data-target="#enable" data-action="enable" data-id="{{$user->id}}">
                                                <button type="button" class="btn btn-link btn-actions" data-toggle="tooltip" data-placement="top" data-title="Activar">
                                                    <i class="fad fa-user-check fa-lg"></i>
                                                </button>
                                            </span>
                                        @endif
                                    @else
                                        <span class="open-modal" data-toggle="modal" data-target="#authorize" data-action="authorize" data-id="{{$user->id}}">
                                            <button type="button" class="btn btn-link btn-actions" data-toggle="tooltip" data-placement="top" data-title="Autorizar">
                                                <i class="fad fa-shield-check fa-lg"></i>
                                            </button>
                                        </span>
                                    @endif


                                    <a href="{{route('users.edit', ['id' => $user->id])}}" class="btn btn-link btn-actions" data-toggle="tooltip" data-placement="top" data-title="Editar">
                                        <i class="fad fa-user-edit fa-lg"></i>
                                    </a>

                                    <span class="open-modal" data-toggle="modal" data-target="#delete" data-action="delete" data-id="{{$user->id}}">
                                        <button type="button" class="btn btn-link btn-actions" data-toggle="tooltip" data-placement="right" data-title="Eliminar">
                                            <i class="fad fa-user-times fa-lg"></i>
                                        </button>
                                    </span>
                                </td>
                            </tr>
                        @endforeach
                    </table>
                </div>
            @else
                <div class="col-12 text-center mt-5 no-records">
                    <i class="fad fa-exclamation-triangle fa-5x mb-3"></i>
                    <h3>{{__('SIN RESULTADOS')}}</h3>
                </div>
            @endif
        </div>
    </div>

    @include('Users.disable')
    @include('Users.authorize')
    @include('Users.enable')
    @include('Users.delete')

@endsection
@section('scripts')
    <script src="{{asset('js/getID.js')}}" charset="utf-8"></script>
    <script type="text/javascript">
        $('#btn-authorize').click(function(){
            $(this).empty().append("<i class='fad fa-spinner fa-pulse mr-3'></i>CARGANDO...");
        });
    </script>
@endsection

resources/views/Users/modal-image.blade.php
<div class="modal fade" id="modal-image" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content modals">
            <div class="modal-header">
                <h5 class="modal-title">{{__('CAMBIAR IMAGEN')}}</h5>
                <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p class="text-center">{{__('Cambiar imagen de usuario')}}</p>
                <div class="input-group mb-3">
                  <div class="custom-file">
                    <input type="file" class="custom-file-input" id="user-image" name="user-image">
                    <label class="custom-file-label" for="user-image" id="image-name" aria-describedby="user-image">{{__('Elegir imagen')}}</label>
                  </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-link text-white text-decoration-none" data-dismiss="modal">{{__('CANCELAR')}}</button>
                <button type="button" class="btn btn-submit rounded-0" name="button" data-dismiss="modal">{{__('ACEPTAR')}}</button>
            </div>
        </div>
    </div>
</div>

resources/views/Users/roles.blade.php
@extends('layouts.app')
@section('lista-personal', 'side-active')
@section('top-title','ROLES')
@section('styles')
    <link rel="stylesheet" href="{{asset('css/layouts/index.css')}}">
    <link rel="stylesheet" href="{{asset('css/layouts/edit.css')}}">
@endsection
@section('content')

    <user-roles v-bind:user="{{ json_encode($user) }}" v-bind:user_roles="{{ json_encode($roles) }}"></user-roles>

@endsection