routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->middleware(['CheckStatus','auth','CheckEntry'])->name('home');
Route::post('/users/store','UserController@store')->name('users.store');

Route::middleware(['auth','role:super-admin|administrador','CheckStatus','CheckEntry'])->prefix('users')->name('users.')->group(function(){
    Route::get('/', 'UserController@index')->name('index');
    Route::get('/user/{id}','UserController@show')->name('show')->where('id','[0-9]+');
    Route::get('/user/{id}/edit','UserController@edit')->name('edit')->where('id','[0-9]+');
    Route::get('/user/{id}/roles','UserController@roles')->name('roles');

    Route::post('/disable','UserController@disable')->name('disable');
    Route::post('/enable','UserController@enable')->name('enable');
    Route::post('/destroy','UserController@destroy')->name('destroy');
    Route::post('/authorize','UserController@authorizeAccount')->name('authorize');
    Route::post('/update/{id}','UserController@update')->where('id','[0-9]+')->name('update');
    Route::post('/roles/{id}/update','UserController@update_roles')->where('id','[0-9]+')->name('roles.update');
});

Route::middleware(['auth','role:super-admin|administrador','CheckStatus','CheckEntry'])->prefix('attendances')->name('attendances.')->group(function(){
    Route::get('/','AttendanceController@index')->name('index');
    Route::any('/registers','AttendanceController@registers')->name('registers');

    Route::post('/store','AttendanceController@store')->name('store');
    Route::post('departiture','AttendanceController@departiture')->name('departiture');
});

Route::middleware(['auth','role:super-admin|administrador|cocina','CheckStatus','CheckEntry'])->prefix('stews')->name('stews.')->group(function(){
    Route::get('/','StewController@index')->name('index');

    Route::post('/store','StewController@store')->name('store');
    Route::post('/disable/{id}','StewController@disable')->name('disable')->where('id','[0-9]+');
    Route::post('/enable/{id}','StewController@enable')->name('enable')->where('id','[0-9]+');
});

app/Attendance.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Attendance extends Model
{
    public function user(){
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/AttendanceController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Attendance;
use App\User;
use Carbon\Carbon;

class AttendanceController extends Controller
{
    public function index(Request $request)
    {
        $search = $request->input('search');
        $date = Carbon::now()->isoFormat('YYYY-MM-DD');
        $attendances = Attendance::select('*','attendances.id as id')
                            ->join('users','attendances.user_id','users.id')
                            ->where(DB::raw("CONCAT(names,' ',paternal_surname,' ',maternal_surname)"),'like',"%$search%")
                            ->where('attendances.date',$date)
                            ->get();

        foreach ($attendances as $attendance) {
            $start = new Carbon('07:00:00');
            if(Carbon::parse($attendance->entry)->gt($start)){
                $difference = $start->diff($attendance->entry)->format('%H:%I:%S');
            }else{
                $difference = 'SIN RETARDO';
            }
            $attendance->difference = $difference;
        }
        $users = User::whereStatus(true)->whereAuthorized(true)->get();

        return view('Attendances.index', compact('attendances','search','users'));
    }

    public function store(Request $request)
    {
        $request->validate([
            'user_id' => 'required|exists:users,id'
        ],[
            'user_id.required' => 'El usuario es requerido',
            'user_id.exists'   => 'El usuario seleccionado no existe'
        ]);

        $now = Carbon::now()->isoFormat('YYYY-MM-DD');
        $verify = Attendance::where('date','=',$now)->whereUser_id($request->user_id)->whereStatus(true)->first();
        if(!is_null($verify))
            return redirect()->route('attendances.index')->withErrors('La entrada del usuario seleccionado ya fue registrada');

        $attendace = new Attendance();
        $attendace->user_id = $request->user_id;
        $attendace->date    = $now;
        $attendace->entry   = Carbon::now()->format('H:i:s');
        $attendace->status  = true;

        $attendace->save();

        return redirect()->route('attendances.index')->withStatus('Entrada registrada correctamente');
    }

    public function departiture(Request $request)
    {
        $attendance = Attendance::findOrfail($request->id);
        $attendance->departure = Carbon::now()->format('H:i:s');
        $attendance->status = false;

        $attendance->update();
        return redirect()->route('attendances.index')->withStatus('Salida registrada correctamente');
    }


    public function registers(Request $request)
    {
        if($request->ajax()):
            $attendances = Attendance::where('date','>=',$request->initial_date)->where('date','<=',$request->final_date)->with(['user'])->get();
            return response()->json(['attendances' => $attendances],200);
        endif;
        return view('Attendances.attendances');
    }
}

resources/views/Attendances/attendance.blade.php
<div class="modal fade" id="attendance" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content modals">
            <div class="modal-header">
                <h5 class="modal-title">{{__('REGISTRO DE ENTRADA')}}</h5>
                <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form class="" action="{{ route('attendances.store') }}" method="post">
                @csrf
                <div class="modal-body">
                    <div class="form-group">
                        <select class="form-control form-select" name="user_id" required>
                            <option value="" selected disabled>{{__('Seleccione un usuario')}}</option>
                            @foreach ($users as $user)
                                <option value="{{$user->id}}">{{$user->names}}</option>
                            @endforeach
                        </select>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-link text-white text-decoration-none" data-dismiss="modal">{{__('CANCELAR')}}</button>
                    <button type="submit" class="btn btn-submit rounded-0" name="button">{{__('ACEPTAR')}}</button>
                </div>
            </form>
        </div>
    </div>
</div>

resources/views/Attendances/attendances.blade.php
@extends('layouts.app')
@section('attendance', 'side-active')
@section('top-title','LISTA DE PERSONAL')
@section('styles')
    <link rel="stylesheet" href="{{asset('css/layouts/index.css')}}">
    <link rel="stylesheet" href="{{asset('css/layouts/edit.css')}}">

@endsection
@section('content')

    <attendances></attendances>

@endsection

resources/views/Attendances/departiture.blade.php
<div class="modal fade" id="departiture" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content modals">
            <div class="modal-header">
                <h5 class="modal-title">{{__('ATENCIÓN')}}</h5>
                <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="{{route('attendances.departiture')}}" method="post">
                @csrf
                <div class="modal-body text-center">
                    <input type="hidden" name="id" id="attendance-id" value="">
                    <p>{{__('¿Realmente desea registrar la hora de salida?')}}</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-link btn-cancelar text-decoration-none" data-dismiss="modal">
                        {{__('CANCELAR')}}
                    </button>
                    <button type="submit" class="btn btn-aceptar">
                        {{__('ACEPTAR')}}
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

resources/views/Attendances/index.blade.php
@extends('layouts.app')
@section('attendance', 'side-active')
@section('top-title','LISTA DE PERSONAL')
@section('styles')
    <link rel="stylesheet" href="{{asset('css/layouts/index.css')}}">
@endsection
@section('content')

    <div class="container-fluid">
        <div class="row">
            <div class="col-12 px-4 form-row mt-4">
                <div class="col-lg-6 mb-3">
                    <form class="form-row" action="" method="get">
                        <div class="form-group col-11 col-md-8 mb-0 pr-0">
                            <input type="text" class="form-control search-input" name="search" value="{{$search}}" placeholder="Buscar...">
                        </div>
                        <button type="submit" class="btn btn-search col-1">
                            <i class="fas fa-search"></i>
                        </button>
                    </form>
                </div>

                <div class="col-lg-6 text-right px-0">
                    <a href="{{route('attendances.registers')}}" class="btn btn-new-entry rounded-0">
                        REGISTROS
                    </a>
                    <button data-toggle="modal" data-target="#attendance" class="btn btn-new-entry px-4 rounded-0">{{__('REGISTRAR ENTRADA')}}</button>
                </div>
            </div>

            @if($attendances->count())

                <div class="col-12 table-responsive mt-4">
                    <table class="table">
                        <thead>
                            <tr class="text-center">
                                <th>{{__('Usuario')}}</th>
                                <th>{{__('Entrada')}}</th>
                                <th>{{__('Salida')}}</th>
                                <th>{{__('Retardo')}}</th>
                                <th>{{__('Acciones')}}</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($attendances as $attendance)
                                <tr class="text-center">
                                    <td class="align-middle text-truncate">{{$attendance->user->names}}</td>
                                    <td class="align-middle text-truncate">{{$attendance->entry}}</td>
                                    <td class="align-middle text-truncate">{{$attendance->departure ?? 'PENDIENTE'}}</td>
                                    <td class="align-middle text-truncate @if($attendance->difference != 'SIN RETARDO') table-danger text-dark @endif">{{$attendance->difference}}</td>
                                    <td class="align-middle text-truncate">
                                        @if($attendance->departure == null)
                                            <span class="open-modal" data-toggle="modal" data-target="#departiture" data-action="departiture" data-id="{{$attendance->id}}">
                                                <button type="button" class="btn btn-link btn-actions" name="button" data-toggle="tooltip" data-placement="right" data-title="Registrar salida">
                                                    <i class="fad fa-user-tag fa-lg"></i>
                                                </button>
                                            </span>
                                        @endif
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>

            @endif
        </div>
    </div>

    @include('Attendances.attendance')
    @include('Attendances.departiture')

@endsection
@section('scripts')
    <script src="{{asset('js/getID.js')}}" charset="utf-8"></script>
@endsection