routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->middleware(['CheckStatus','auth','CheckEntry'])->name('home');
Route::post('/users/store','UserController@store')->name('users.store');

Route::middleware(['auth','role:super-admin|administrador','CheckStatus','CheckEntry'])->prefix('users')->name('users.')->group(function(){
    Route::get('/', 'UserController@index')->name('index');
    Route::get('/user/{id}','UserController@show')->name('show')->where('id','[0-9]+');
    Route::get('/user/{id}/edit','UserController@edit')->name('edit')->where('id','[0-9]+');
    Route::get('/user/{id}/roles','UserController@roles')->name('roles');

    Route::post('/disable','UserController@disable')->name('disable');
    Route::post('/enable','UserController@enable')->name('enable');
    Route::post('/destroy','UserController@destroy')->name('destroy');
    Route::post('/authorize','UserController@authorizeAccount')->name('authorize');
    Route::post('/update/{id}','UserController@update')->where('id','[0-9]+')->name('update');
    Route::post('/roles/{id}/update','UserController@update_roles')->where('id','[0-9]+')->name('roles.update');
});

Route::middleware(['auth','role:super-admin|administrador','CheckStatus','CheckEntry'])->prefix('attendances')->name('attendances.')->group(function(){
    Route::get('/','AttendanceController@index')->name('index');
    Route::any('/registers','AttendanceController@registers')->name('registers');

    Route::post('/store','AttendanceController@store')->name('store');
    Route::post('departiture','AttendanceController@departiture')->name('departiture');
});

Route::middleware(['auth','role:super-admin|administrador|cocina','CheckStatus','CheckEntry'])->prefix('stews')->name('stews.')->group(function(){
    Route::get('/','StewController@index')->name('index');

    Route::post('/store','StewController@store')->name('store');
    Route::post('/disable/{id}','StewController@disable')->name('disable')->where('id','[0-9]+');
    Route::post('/enable/{id}','StewController@enable')->name('enable')->where('id','[0-9]+');
});

app/Stew.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Stew extends Model
{
    //
}

app/Http/Controllers/StewController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Stew;

class StewController extends Controller
{
    public function index(Request $request)
    {
        $search = $request->input('search');
        $stews = Stew::where('name','like',"%$search%")->get();
        return view('Stews.index',compact('search','stews'));
    }

    public function store(Request $request)
    {

        $stew = new Stew();
        $stew->name = $request->name;
        $stew->save();

        return redirect()->route('stews.index')->withStatus('Guisado registrado correctamente');
    }

    public function disable($id)
    {
        $stew = Stew::findOrfail($id);
        $stew->status = false;
        $stew->update();

        return redirect()->route('stews.index')->withStatus('Guisado desactivado correctamente');
    }

    public function enable($id){
        $stew = Stew::findOrfail($id);
        $stew->status = true;
        $stew->update();

        return redirect()->route('stews.index')->withStatus('Guisado activado correctamente');
    }
}

resources/views/Stews/create.blade.php
<div class="modal fade" id="create" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content modals">
            <div class="modal-header">
                <h5 class="modal-title">NUEVO GUISADO</h5>
                <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="{{route('stews.store')}}" method="post">
                @csrf
                <div class="modal-body">
                    <div class="form-group">
                        <input type="text" class="form-control create-input" name="name" placeholder="Nombre del guisado" required>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-link text-white text-decoration-none" data-dismiss="modal">{{__('CANCELAR')}}</button>
                    <button type="submit" class="btn btn-submit rounded-0" name="button">{{__('ACEPTAR')}}</button>
                </div>
            </form>
        </div>
    </div>
</div>

resources/views/Stews/index.blade.php
@extends('layouts.app')
@section('attendance', 'side-active')
@section('top-title','GUISADOS')
@section('styles')
    <link rel="stylesheet" href="{{asset('css/layouts/index.css')}}">
@endsection
@section('content')

    <div class="container-fluid">
        <div class="row">
            <div class="col-12 px-4 form-row mt-4">
                <div class="col-lg-6 mb-3">
                    <form class="form-row" action="" method="get">
                        <div class="form-group col-11 col-md-8 mb-0 pr-0">
                            <input type="text" class="form-control search-input" name="search" value="{{$search}}" placeholder="Buscar...">
                        </div>
                        <button type="submit" class="btn btn-search col-1">
                            <i class="fas fa-search"></i>
                        </button>
                    </form>
                </div>

                <div class="col-lg-6 text-right px-0">
                    <a href="#" data-toggle="modal" data-target="#create" class="btn btn-new-entry px-4 rounded-0">{{__('NUEVO REGISTRO')}}</a>
                </div>
            </div>

            @if($stews->count())
                <div class="col-12 table-responsive mt-4">
                    <table class="table">
                        <thead>
                            <tr class="text-center">
                                <th>{{__('ID')}}</th>
                                <th>{{__('Nombre')}}</th>
                                <th>{{__('Estatus')}}</th>
                                <th>{{__('Acciones')}}</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($stews as $stew)
                                <tr class="text-center">
                                    <td class="align-middle text-truncate">{{ $stew->id }}</td>
                                    <td class="align-middle text-truncate">{{ $stew->name }}</td>
                                    <td class="align-middle text-truncate text-dark {{ $stew->status ? 'table-success' : 'table-danger' }}">
                                        @if($stew->status)
                                            {{__('Disponible')}}
                                        @else
                                            {{__('No Disponible')}}
                                        @endif
                                    </td>
                                    <td class="align-middle text-truncate">
                                        @if($stew->status)
                                            <form class="" action="{{ route('stews.disable',['id' => $stew->id]) }}" method="post">
                                                @csrf
                                                <button type="submit" class="btn btn-link btn-actions" name="button" data-toggle="tooltip" data-placement="left" data-title="Desactivar">
                                                    <i class="fad fa-times fa-lg"></i>
                                                </button>
                                            </form>
                                        @else
                                            <form class="" action="{{ route('stews.enable',['id' => $stew->id]) }}" method="post">
                                                @csrf
                                                <button type="submit" class="btn btn-link btn-actions" name="button" data-toggle="tooltip" data-placement="left" data-title="Activar">
                                                    <i class="fad fa-check-square fa-lg"></i>
                                                </button>
                                            </form>
                                        @endif
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            @else
                <div class="col-12 text-center mt-5 no-records">
                    <i class="fad fa-exclamation-triangle fa-5x mb-3"></i>
                    <h3>{{__('SIN RESULTADOS')}}</h3>
                </div>
            @endif
        </div>
    </div>

    @include('Stews.create');

@endsection